vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: 'app.path.article'     
            upload_destination: '%kernel.project_dir%/public%app.path.article%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer